services:
  system_db:
    env_file:
      - systemdb.env
    image: postgres:17-alpine
    container_name: system_db
    restart: always
    ports:
      - '5436:5432'
    volumes:
      - system_db_data:/var/lib/postgresql/data
      # - ./data/systemdb_init.sql:/docker-entrypoint-initdb.d/0-systemdb_init.sql
    networks:
      - default

  vector_db:
    env_file:
      - vectordb.env
    image: pgvector/pgvector:pg17
    container_name: vector_db
    restart: always
    ports:
      - '5437:5432'
    volumes:
      - vector_db_data:/var/lib/postgresql/data
      # - ./data/vectordb_init.sql:/docker-entrypoint-initdb.d/0-vectordb_init.sql
    networks:
      - default
  
  northwind:
    env_file:
      - northwind.env
    image: manchestercodes/northwind
    container_name: northwind_db
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - northwind_data:/var/lib/mysql
    networks:
      - default

volumes:
  vector_db_data:
  system_db_data:
  northwind_data:
