name: Build and Deploy .NET 8 API to VDS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore "DatabaseReportingSystem.API/DatabaseReportingSystem.API.csproj" --configfile nuget.config --ignore-failed-sources

    - name: Build Project
      run: dotnet publish -c Release -o out

    - name: Archive Build Artifacts
      run: tar -czf app.tar.gz -C out .
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-tarball
        path: app.tar.gz

  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-tarball

      # Copy files to server using SCP
      - name: Copy Archive to VDS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VDS_URI }}
          username: ${{ secrets.VDS_USERNAME }}
          password: ${{ secrets.VDS_PASSWORD }}
          source: ./app.tar.gz
          target: /var/www/drs-api/

      # Restart API
      - name: Restart Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VDS_URI }}
          username: ${{ secrets.VDS_USERNAME }}
          password: ${{ secrets.VDS_PASSWORD }}
          script: |
            cd /var/www/drs-api/
            tar -xzf app.tar.gz
            rm app.tar.gz
            
            # Gracefully terminate the existing process
            if pgrep -f 'dotnet /var/www/drs-api/DatabaseReportingSystem.API.dll'; then
              pkill -SIGINT -f 'dotnet /var/www/drs-api/DatabaseReportingSystem.API.dll'
              sleep 5  # Allow time for graceful shutdown
            fi
      
            # Restart the application
            set -o allexport
            source ~/api.env
            set +o allexport
            nohup dotnet /var/www/drs-api/DatabaseReportingSystem.API.dll > /var/www/drs-api/log.txt 2>&1 &
