name: Build, Push and Deploy .NET 8 API to VDS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to DockerHub or private container registry
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_CONTAINER_NAME }}:latest .

      # Push Docker image to DockerHub
      - name: Push Docker Image to DockerHub
        run: |
          docker tag ${{ vars.DOCKER_CONTAINER_NAME }}:latest ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_CONTAINER_NAME }}:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_CONTAINER_NAME }}:latest

  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # SSH into VDS and deploy
      - name: Deploy to VDS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VDS_URI }}
          username: ${{ secrets.VDS_USERNAME }}
          password: ${{ secrets.VDS_PASSWORD }}
          script: |
            docker pull ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_CONTAINER_NAME }}:latest
            docker compose up -d
