name: Build and Deploy to VDS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Dotnet 8 SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore API dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build project
      - name: Build Project
        run: dotnet publish -c Release -o out

      # Copy files to server using SCP
      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.2.0
        with:
          host: ${{ secrets.VDS_URI }}
          username: ${{ secrets.VDS_USERNAME }}
          password: ${{ secrets.VDS_PASSWORD }}
          source: ./out/
          target: /var/www/drs-api/

      # Restart API
      - name: Restart Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VDS_URI }}
          username: ${{ secrets.VDS_USERNAME }}
          password: ${{ secrets.VDS_PASSWORD }}
          script: |
            pkill -f 'dotnet /var/www/drs-api/DatabaseReportingSystem.API.dll' || true
            nohup dotnet /var/www/drs-api/DatabaseReportingSystem.API.dll > /var/www/drs-api/log.txt 2>&1 &
